.gitignore
benchmark.gd
gdscript/packed_string_array.gd
gdscript/packed_string_array.tscn
gdscript/typed_int_array.gd
gdscript/typed_int_array.tscn
gdscript/typed_string_array.gd
gdscript/typed_string_array.tscn
gdscript/untyped_int_array.gd
gdscript/untyped_int_array.tscn
gdscript/untyped_string_array.gd
gdscript/untyped_string_array.tscn
main.gd
main.tscn
manager.gd
project.godot
rendering/culling/basic_cull.tscn
rendering/culling/culling_base.gd
rendering/culling/directional_light_cull.tscn
rendering/culling/dynamic_cull.tscn
rendering/culling/dynamic_light_cull.gd
rendering/culling/dynamic_light_cull.tscn
rendering/culling/dynamic_light_cull_withs_shadows.tscn
rendering/culling/static_light_cull.tscn

- Add wall clock time measurement on benchmarks.
- This is useful for tests that don't have a time limit, but also for tests with a time limit to ensure the time limit is respected. This information is saved to JSON, so that when you share the JSON sample, the time spent on each test is included.
- Allow tests to not have a predefined time limit.
- This is required for scripting tests.
- Fix culling tests not reporting GPU time (not shown on the preview).
- Update `.gitignore` for Godot 4.0.
*The wall clock time has some inaccuracies (see the tests that took 9 seconds instead of 8) – it doesn't always happen, though. It would be good to figure out why this happens.*

Add initial GDScript tests

---

CONTRIBUTING.md
LICENSE.md
README.md

The instructions could be streamlined in the future (such as by turning `benchmark.gd` into an instanced `benchmark.tscn` scene), but this seems simple enough for now.

Add a guide on contributing new benchmarks

---

main.gd
main.tscn
manager.gd
project.godot

**Depends on https://github.com/godotengine/godot-benchmarks/pull/6 (hence this PR being marked as draft).** Only changes from the second commit should be reviewed here.
- Change window title every time a new benchmark is run to indicate progress.
- Tweak UI display to fit changes in the `master` branch.

Implement running benchmarks from the command line with `--run-benchmarks`

---

README.md
main.gd
main.tscn
manager.gd
project.godot

- Automatically quit on end when using `--run-benchmarks` CLI argument.
- Improve command line printing to be more helpful and descriptive.
- Add documentation on running benchmarks in the README.

Add command line arguments to include/exclude specific benchmarks

---

main.gd
main.tscn
manager.gd
project.godot

Follow-up to https://github.com/godotengine/godot-benchmarks/pull/12 (can be merged independently).
- Use a fixed 1920×1080 viewport size for consistent results.
- `--resolution` CLI argument can be used to override this if needed. It may be a good idea to note the window size in the results JSON too.
- Hardcode the benchmark duration to 5 seconds for benchmarks that have a time limit for consistent results.
- We can consider adding a CLI argument to override this if needed (also noting the value in the results JSON).
- Move the Select All and Select None button next to the "Available Benchmarks:" label, as they're closer to the checkboxes this way.
- Make buttons larger to be easier to click.
- Only show the Copy JSON to Clipboard button after running benchmarks.

Improve benchmark UI and settings for consistency

---

manager.gd

Consolidates `begin_test()`, `end_test()`, and `_process()`, along with the ~nine~ fourteen global variables used to coordinate them, into a single much more linear `run_test()` function

Refactor benchmark code in manager.gd to use coroutines

---

benchmarks/rendering/polygon_2d/1000_polygon_2d.gd
benchmarks/rendering/polygon_2d/1000_polygon_2d.tscn
benchmarks/rendering/polygon_2d/100_polygon_2d.gd
benchmarks/rendering/polygon_2d/100_polygon_2d.tscn
benchmarks/rendering/polygon_2d/10_polygon_2d.gd
benchmarks/rendering/polygon_2d/10_polygon_2d.tscn
benchmarks/rendering/polygon_2d/_polygon_2d.tscn
benchmarks/rendering/polygon_2d/polygon_2d_base.gd

Part of #11. Instantiates either 10, 100, or 1000 Polygon2D's, depending on the benchmark. The polygons are randomly scaled and have 32 vertices.

Add Polygon2D benchmarks

---

benchmarks/rendering/lights_and_meshes.gd

Benchmarks different combinations of lights and meshes. Depends on #22
https://user-images.githubusercontent.com/103326468/218822755-9b0810b2-0bd2-4af8-8850-65eefa486263.mp4
Implements several benchmarks from #11:
> ### 3D Rendering
> 
> * [ ]  50 BoxMeshes
> * [ ]  500 BoxMeshes
> * [ ]  5,000 BoxMeshes
> * [ ]  10 SphereMeshes
> * [ ]  100 SphereMeshes
> * [ ]  1,000 SphereMeshes
> * [ ]  50 OmniLight3Ds without shadows
> * [ ]  50 SpotLight3Ds without shadows

Add lights and meshes benchmark

---

README.md
main.gd
manager.gd

Bundled together into one PR since it's hard to keep separate branches for a codebase this small without running into self-conflicts. Depends on #22 , which the first three commits are part of.
The commits should be fairly self-explanatory. If there's any that you disagree with, let me know and I'll rebase them out.

Miscellaneous cleanup

---

benchmarks/rendering/culling.gd
benchmarks/rendering/polygon_2d.gd

`get_tree().root.size` was returning the window dimensions, presumably the intent was to use the viewport dimensions `get_tree().root.get_visible_rect().size`
Also fixes polygon_2d scenes being off center.

Fix incorrect positioning of objects in some benchmarks

---

benchmarks/rendering/hlod.gd
project.godot

Benchmarks very deep HLODs and their interactions with culling (both occlusion and frustum). Also includes some debugging features out-of-the-box for convenience sake.
Currently hangs unless NUMBER_OF_OBJECTS is set to something smaller like 1000.
Contains commits from #22 for ease of cloning.
https://user-images.githubusercontent.com/103326468/208284510-89e4bf1b-5e5f-4a68-b316-6f944420ea0e.mp4

Add HLOD benchmarks

---

benchmarks/core/config_file.gd
benchmarks/core/node_path.gd
benchmarks/core/string_name.gd

Implements the following benchmarks in the `Core` section from #36  : 
🟪Algorithm🟪 StringNames: Creating and freeing 1000 StringNames
🟪Algorithm🟪 NodePaths: Creating and freeing 1000 NodePaths
~~🟪Algorithm🟪 Strings: Create a benchmark that runs all complex search/merge/etc string operations 50 times.~~
🟪Algorithm🟪 ConfigFileSave / ConfigFileLoad: Create a ConfigFile full of fields and sections (1000). Benchmark saving and benchmark loading.
NB: 1000 iterations for `NodePath` and `StringName` was too small and insignificant, so I bumped that up to 1M.
**Edit**: I did create a `string_manipulation.gd` in the `core` dir that tests most `String` methods, but it turns out, it was already done in the `gdscript` directory. So I removed mine, thus the strikethrough above.

Implement Core benchmarks

---

benchmarks/math/delaunay_2d.gd

- Implements 🟪**Algorithm**🟪 **_Delaunay2D_**: `Delaunay 1000 points in 2D` benchmark of the **Math** category proposed in #36.

Implement a benchmark algorithm `Delaunay2D`

---

benchmarks/math/triangulate.gd

- Implements 🟪**Algorithm**🟪 **_Triangulate_**: `Triangulate a circle of 1000 points` benchmark of the **Math** category proposed in #36.

Implement a benchmark algorithm `Triangulate`

---

benchmarks/core/crypto.gd

`benchmark_generate_1g_random_bytes` takes way too long to finish (on my machine I aborted the benchmark after around 15 minutes so I don't know when/whether it would finish).
The reason: it generates 1G random bytes 100_000 times, which is obviously a bit too much.
I adjusted the random byte benchmarks and made their name more descriptive. All of them finish in 1500 - 3000ms on my machine now.
Revised benchmarks:

Fix Crypto benchmark taking too long

---

benchmarks/gdscript/for_loop.gd
benchmarks/gdscript/lambda_performance.gd

Implements
🟪Algorithm🟪 [Simple for loop add]: GDscript: Run 1,000,000 iterations of a for loop adding a number.
🟪Algorithm🟪 [Simple for loop call]: GDScript: Run 1,000,000 iterations calling a function.
🟪Algorithm🟪 [Lambda performance]: GDscript: Make a simple lambda function and call it 1000 times.
from GDScript section in #36 benchmarks list.

Implement some GDScript benchmarks

---

project.godot

This PR prevents users from seeing a warning about the project using an older version of Godot when loading.
I'm not sure if the inclusion of the `dotnet` config is welcome:
```tscn
[dotnet]
project/assembly_name="Godot Benchmarks"
```
I assume it got added due to me using a Mono build, but I see no downside to adding it to the project config file.

Update project to the current stable version of Godot (4.2)

---

benchmarks/rendering/sponza.gd

Avoid repeating Sponza: it was once for the script name and another on each method's name.

Sponza test names cleanup

---

benchmarks/rendering/sponza.gd

Sample results running on a Mac mini M2:

add sponza AA benchmarks (FSR2, FXAA, MSAA, TAA)

---

benchmarks/math/noise.gd

Reference results from M2 mac mini:

add benchmarks for noise

---

benchmarks/math/convex_hull_3d.gd

The benchmark was bogus before. I missed this error:
convex_hull_3d.gd:34 @ _bench_convex(): Ignoring surface 0, incorrect vertex count: 10000 (for PRIMITIVE_TRIANGLES).
<C++ Error>    Condition "(len % 3) != 0" is true. Continuing.
Also tweaked the iteration count so it takes a reasonable time.
---
Fixes benchmarks introduced in #51.
Reference results on Mac M2:

fix convex hull benchmarks (multiple of 3)

---

benchmarks/scene_nodes/add_children.gd
benchmarks/scene_nodes/delete_children.gd
benchmarks/scene_nodes/get_node.gd
benchmarks/scene_nodes/move_children.gd

Implements
🟪Algorithm🟪 [Adding 5000 children]: Unnamed: Adding 5000 random children nodes without name.
🟪Algorithm🟪 [Adding 5000 children]: Named: Adding 5000 random children nodes with the same name (let the conflict resolution happen).
🟪Algorithm🟪 Moving node children: Move 5000 children nodes between two random positions 5000 times.
🟪Algorithm🟪 [Delete children]: in order: Remove all 5000 children in order, first to last.
🟪Algorithm🟪 [Delete children]: in reverse order: Remove all 5000 children in order, last to first.
🟪Algorithm🟪 [Delete children]: in random order: Remove all 5000 children in random order.
🟪Algorithm🟪 Get node: Create a complex scene hierarchy of 1000 nodes with random nesting, Obtain paths of all nodes, test performance of get_node() for each one from root node.
from …

Implement scene nodes benchmarks

---

benchmarks/math/delaunay_3d.gd

- Implements 🟪**Algorithm**🟪 **_Delaunay3D_**: `Delaunay 1000 points in 3D` benchmark of the **Math** category proposed in #36.
- Depends on https://github.com/godotengine/godot/pull/83353.

Implement a benchmark algorithm `Delaunay3D`

---

benchmarks/viewport/activation.gd
benchmarks/viewport/allocation.gd
manager.gd

This benchmark shows a large variability across gpu drivers and devices with regard to creating and 'activating' subviewports.
'Activating' a subviewport involves creating a SubViewport node, adding it to the scene tree and rendering a frame.
These benchmarks test three levels of strain on the system by creating 'a few' (64) 'many' (256) and 'too many' (1024) subviewports in different benchmarks.
(after running these benchmarks I reduced the viewport size to 512x512 as I noticed the memory usage for 1024x1024 x 1024 subviewports was _rediculous_)
```
Godot v4.3.dev5 - Windows 10.0.22631 - Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 Threads)
1: Vulkan 1.3.215 - Forward+ - Using Device #0: Intel - Intel(R) UHD Graphics 620
2: OpenGL API 3.3.0 - Build 31.0.101.2115 - Compatibility - Using …
```

Add benchmark for viewport creation/activation

---

benchmarks/rendering/particles_2d.gd

Part of #11. Creates 10 GPUParticles2D nodes that each emit 1000 particles, or 1000 GPUParticles2D nodes that each emit 10 particles. Same goes for the CPUParticles2D benchmarks, converted to CPUParticles2D nodes.

Add GPUParticles2D and CPUParticles2D benchmarks

---

benchmarks/gdscript/binary_trees.gd
benchmarks/gdscript/hello_world.gd
benchmarks/gdscript/mandelbrot_set.gd
benchmarks/gdscript/merkle_trees.gd
benchmarks/gdscript/nbody.gd
benchmarks/gdscript/spectral_norm.gd

Adds these benchmarks from #36:
- 🟪Algorithm🟪 [Calculate Mandlebrot set]: GDscript: for fixed size image, and time it.
- 🟪Algorithm🟪 [Port these benchmarks]: GDscript: https://programming-language-benchmarks.vercel.app/lua
6 new benchmarks have been added.:
| Name      | Input 1 | Input 2 | Input 3 |
| ----------- | ----------- |----------- |----------- |
| Mandelbrot set algorithm | 600x400 image, 1000 iterations |
| Binary trees | 15 | 18 |
| Hello world |
| Merkle trees | 13 | 15 |
| Nbody | 500000 | 1000000 |
| Spectral norm| 100 | 500 | 1000 |
For the merkle trees, nbody and spectral norm benchmarks, I decided to give inputs lower than those in https://programming-language-benchmarks.vercel.app/lua, as GDScript was taking too long to finish them.
<details>
<summary>Results on my …

Add Mandelbrot set and Lua ported algorithm benchmarks

---

benchmarks/rendering/canvas_item.gd

Adds the following benchmarks from #36:
- 🟥CPU🟥 [CanvasItem]: Rendering: Draw different shapes (images, circles, etc) using the CanvasItem 2D drawing API. Draw 5000 elements. Measure performance.
- 🟥CPU🟥 [CanvasItem]: Re-Rendering: Same as above, but every frame call queue_update() so it redraws. Measure performance.
I am quite puzzled as to why drawing the elements once sometimes results in more CPU & GPU time, than re-rendering them every frame. I added benchmarks for 10000 and 20000 elements in case 5000 is too low and it's being affected by an error margin, but I still get weird results for these benchmarks as well. Not sure if I'm doing something wrong, the logic seems fine to me, but let me know if I should keep or remove the benchmarks for 10000 & 20000 elements.
<details> …

Add CanvasItem drawing benchmarks

---

benchmark.gd
benchmarks/physics/area_2d.gd
benchmarks/physics/character_body_2d.gd
benchmarks/physics/rigid_body_2d.gd
benchmarks/physics/rigid_body_3d.gd
manager.gd

This allows individual benchmarks to change the benchmark time limit, which is requested for certain benchmarks, such as the physics ones (#72). Benchmarks that don't return a node are still unaffected by the limit, although I could change this if desired. This PR also sets the timer of all physics benchmarks to 10 seconds. `rigid_body_2d.gd` doesn't actually have any changes besides this, the rest of the changes were formatting made by the Godot editor itself.

Allow the benchmark time limit to be changed by individual benchmarks

---

benchmarks/animation/tween.gd

Adds the following benchmarks from #36:
- 🟥CPU🟥 Tweens: Animate 100 properties with a Tween
- 🟥CPU🟥 Tween Methods: Animate 1000 Tweens using tween_method().
<details>
<summary>Results on my PC</summary>
{
{
"benchmarks": [
{
"category": "Animation > Tween",
"name": "Animate 1000 Tween Methods",
"results": {
"render_cpu": 0.2367,
"time": 4.908
}
},
{
"category": "Animation > Tween",
"name": "Tween 100 Properties",
"results": {
"render_cpu": 0.03256,
"time": 0.599
}
}
],
"engine": {
"version": "v4.3.beta1.official",
"version_hash": "a4f2ea91a1bd18f70a43ff4c1377db49b56bc3f0"
},
"system": {
"cpu_architecture": "x86_64",
"cpu_count": 12,
"cpu_name": "AMD Ryzen 5 1600 Six-Core Processor",
"os": "Linux"
}
}
</details>

Add tween animation benchmarks

---

benchmarks/rendering/culling.gd
benchmarks/rendering/lightmap_probe_influence.gd

Adds the following benchmarks from #36:
- 🟥CPU🟥 [Cull]: Rotating: Cull 10k rotating objects
- 🟥CPU🟥 [Cull Omni Shadows]: Static: Cull 10k objects, 200 omni lights with shadows, static
- 🟥CPU🟥 [Cull Spot Shadows]: Static: Cull 10k objects, 200 omni lights with shadows, static
- 🟥CPU🟥 [Cull Spot Shadows]: Dynamic: Cull 10k objects, 200 omni lights with shadows, lights move around.
- 🟥CPU🟥 Lightmap probe influence : Simple scene baked with lightmaps (and using tons of probes, like 500), 1000 objects moving around receiving influence from probes.
The rest of the CPU benchmarks under 3D rendering seem to be already implemented in culling.gd
I also formatted culling.gd and improved its static typing.
<details>
<summary>Results on my PC</summary>
{
"benchmarks": [
{
"category": "Rendering > …

Add cull and lightmap probe influence benchmarks

---

benchmarks/core/array.gd

Adding benchmarks related to `Array` this was done as part of https://github.com/godotengine/godot/pull/93276

Benchmark Array functions

---

benchmarks/gdscript/binary_trees.gd
benchmarks/gdscript/spectral_norm.gd

The spectral norm algorithm benchmark implemented in #68 had the wrong inputs. My bad! 😅
EDIT: I also improved its static typing, making it run quite faster.

Fix mistakes with binary trees & spectral norm

---

Benchmark.cs
benchmarks/csharp/physics/RigidBody2D.cs
benchmarks/csharp/physics/RigidBody3D.cs
manager.gd

Continuation of #73, fixes a crash when running C# physics benchmarks. Also sets the C# physics benchmarks to 10 seconds.

Fix C# benchmarks not being able to be loaded, and implement the ability to change the benchmark time limit

---

benchmarks/navigation/moving_agents_2d.gd
benchmarks/navigation/moving_agents_3d.gd
benchmarks/physics/area_2d.gd
benchmarks/physics/area_3d.gd
benchmarks/physics/character_body_2d.gd
benchmarks/physics/character_body_3d.gd
benchmarks/physics/rigid_body_2d.gd
benchmarks/physics/rigid_body_3d.gd
benchmarks/physics/softbody_3d.gd
benchmarks/physics/triangle_mesh.gd
main.gd
manager.gd

To make it easier to just check CPU usage of the navigation system itself, without visuals. ~~The visuals are enabled by default, like they are in the physics benchmarks, but I can make them disabled if desired.~~ EDIT: They are now off by default.

Add a command-line argument to toggle visuals in the physics and navigation agents benchmarks

---

web/README.md
web/layouts/index.html

The user can click "Show all benchmarks..." at the end to reveal the full list of benchmarks.
Benchmarks are also now ordered from newest to oldest, instead of from oldest to newest.
- This closes https://github.com/godotengine/godot-benchmarks/issues/91.

Show the 10 most recent benchmarks on the homepage only at first

---

gdextension/.gitignore

`compile_commands.json` is required for many IDEs and can be generated using `scons compiledb=yes compile_commands.json`.

Add compile_commands.json to gitignore.

---

gdextension/src/benchmarks/array.cpp

Fixes compile issues on macOS `arm64` / clang:
```
In file included from godot-cpp/gen/include/godot_cpp/classes/object.hpp:41:
godot-cpp/include/godot_cpp/variant/typed_array.hpp:58:30: error: type 'long' cannot be used prior to '::' because it has no members
58 |                 set_typed(Variant::OBJECT, T::get_class_static(), Variant());
|                                            ^
src/benchmarks/array.cpp:41:19: note: in instantiation of member function 'godot::TypedArray<long>::TypedArray' requested here
41 |         TypedArray<long> array;
|                          ^
1 error generated.
scons: *** [src/benchmarks/array.os] Error 1
scons: building terminated because of errors.
```

Use int64_t instead of long for int64 TypedArray.

---

gdextension/src/benchmarks/spectral_norm.cpp

Remove include of non-standard and not needed `<malloc.h>`

---

manager.gd

I encountered this bug while trying to export to web. The exported project couldn't recognize benchmarks because Godot remaps resource paths, which resulted in the script paths got from `DirAccess` having a `.remap` suffix. Adding a simple filter fixed the issue.

Fix cannot detect benchmarks in exported version

---

web/layouts/index.html
web/static/graphs.js

This PR fixes the call to `sort()` on Chromium-based browsers, while having no further effect on Firefox (which was working previously).
Tested on MacOS Sequoia Version 15.2 (24C101), with:
1. Chrome - Version 132.0.6834.160 (Official Build) (arm64)
2. Firefox - 129.0.2 (64-bit)
The fix was inspired by freeCodeCamp/freeCodeCamp#34543 .
The Chrome (left) and Firefox (right) browsers are shown side by side below...
For the fixed code (correct behaviour)
For the `main` branch (incorrect sorting only for Chrome)

Fix sorting on Chromium-based browsers

---

gdextension/src/benchmarks/spectral_norm.cpp

PR #103 broke windows builds. The header has been re-added with a preprocessor conditional check for Windows.

Re-added missing header needed for Windows

---

run-benchmarks.sh
web/layouts/benchmark/single.html
web/src-data/graphs.json

- Closes #99.
- Closes #104.
- Requires https://github.com/godotengine/godot-benchmarks-results/pull/3
This is how the beauties are looking:
The small new results tables also (kinda) work for RAM and size:
Shader startup times are currently DEBUG only. It would be good to add RELEASE as a follow-up, I think.

Add graphs for binary size, build time, build memory use, startup time, and memory use.

---

CONTRIBUTING.md
README.md
run-benchmarks.sh

Follow-up of https://github.com/godotengine/godot-docs/pull/11188.
The contents have already been copied to the contributing docs: https://contributing.godotengine.org/en/latest/other/benchmarks.html

Update contributing links and migrate contributing guidelines

---

web/static/graphs.js

This will add a vertical line where Godot 4.5 was released.
Unfortunately, builds are still failing, so changes aren't reaching https://benchmarks.godotengine.org anyway. But it will be there when it's fixed.

Add godot 4.5 release date to graphs.
